/** Tool / place tags for process artifacts — shown in carousel like product module tags */
export const artifactToolTags: Record<string, string[]> = {
  "Problem Statement": ["FigJam", "Workshop"],
  "User Interview": ["Notion", "Research"],
  JTBD: ["FigJam", "Jobs"],
  Hypothesis: ["Notion", "Product"],
  "Success Metrics": ["Notion", "Analytics"],
  "User Interviews": ["Notion", "Research"],
  "Competitor Map": ["FigJam", "Market"],
  Personas: ["FigJam", "UX"],
  Insights: ["Notion", "Synthesis"],
  "User Journey": ["FigJam", "UX"],
  "Feature Map": ["FigJam", "Product"],
  "MVP Scope": ["Notion", "Scope"],
  Roadmap: ["Notion", "Planning"],
  Metrics: ["Notion", "Analytics"],
  "User Flow": ["FigJam", "UX"],
  Wireframes: ["Figma", "UX"],
  "Screen States": ["Figma", "UI"],
  "Edge Cases": ["Notion", "QA"],
  "Prototype Logic": ["Figma", "Prototype"],
  "Design System": ["Figma", "UI"],
  Components: ["Figma", "UI"],
  Typography: ["Figma", "UI"],
  Spacing: ["Figma", "UI"],
  "UI States": ["Figma", "UI"],
  "Prompt System": ["Notion", "AI"],
  "LLM Flow": ["FigJam", "AI"],
  "JSON Structure": ["Notion", "AI"],
  Automation: ["Code", "AI"],
  "QA Logic": ["Notion", "QA"],
  "Clickable Prototype": ["Figma", "Prototype"],
  "Interaction Map": ["FigJam", "UX"],
  "Motion States": ["Figma", "Motion"],
  "Test Build": ["Code", "Build"],
  "Feedback Notes": ["Notion", "Research"],
  "Launch Plan": ["Notion", "Launch"],
  Analytics: ["Notion", "Analytics"],
  "Feedback Loop": ["Notion", "Growth"],
  "Iteration Backlog": ["Notion", "Product"],
};

export function toolsForArtifact(name: string): string[] {
  return artifactToolTags[name] ?? ["Artifact"];
}
