export type Language = "ru" | "en" | "th";

export const content: Record<Language, any> = {
  ru: {
    // Header
    header: {
      title: "VIKTOR.SYSTEM",
      status: "Online",
      messages: [
        "Свободен для нового проекта",
        "Соберу MVP под ключ",
        "Product · UX · AI в одном",
        "Оставь бриф внизу",
        "Отвечу сегодня",
      ],
    },
    // Boot Screen
    boot: {
      title: "VIKTOR.SYSTEM",
      line: "продукты, которые хочется открыть",
      sequence: [
        "Boot sequence...",
        "Loading modules...",
        "AI loaded",
        "Product loaded",
        "Design loaded",
        "Strategy loaded",
        "Automation loaded",
        "System ready",
      ],
    },
    // Hero Section
    hero: {
      title: "Я создаю продукты.",
      subtitle: "От идеи и UX до AI, автоматизации и запуска.",
      tags: ["Продукт", "UX/UI", "AI", "Мобиль", "Web", "Автоматизация"],
      // Quick links → Process stages (1-based stage numbers)
      // stage = 1-based Process stage (UI shows 01–08)
      quickLinks: [
        { label: "Продукт", stage: 3 },
        { label: "UX/UI", stage: 4 },
        { label: "AI", stage: 6 },
        { label: "Мобиль", stage: 7 },
        { label: "Web", stage: 5 },
        { label: "Автоматизация", stage: 8 },
      ],
      cta: {
        explore: "Смотреть продукты",
        contact: "Связаться",
      },
    },
    // The Stack & Capabilities (replaces Track Record)
    stackCapabilities: {
      title: "Стек и возможности",
      subtitle: "Технический арсенал и инструменты для полного цикла разработки",
      cards: [
        {
          id: "design-to-code",
          title: "Дизайн → Код",
          subtitle: "Figma → Xcode",
          description:
            "Проектирую UI/UX в Figma сразу с учётом ограничений SwiftUI/UIKit. Компоненты, стили и автолейауты переносятся в Xcode один в один без потери логики и пикселей. Строгая архитектура от концепта до нативного кода.",
          tags: ["Figma", "Xcode", "SwiftUI", "UIKit", "Design Systems"],
        },
        {
          id: "supercharged-dev",
          title: "Сверхобъёмная разработка",
          subtitle: "Cursor IDE + AI",
          description:
            "Использую Cursor IDE на стероидах. Написал жёсткие кастомные инструкции (.cursorrules) под свои проекты, чтобы AI-ассистент с первого раза генерировал чистый, типизированный код без галлюцинаций. Это заменяет небольшую команду разработки.",
          tags: ["Cursor IDE", "Claude", "GPT-4", "Code Generation"],
        },
        {
          id: "ai-integration",
          title: "Интеграция ИИ",
          subtitle: "Модели и агенты",
          description:
            "Внедряю AI под конкретные задачи интерфейса и логики. Умею комбинировать движки: Claude 3.5 Sonnet — для сложного кода, GPT-4o — для аналитики данных, а также специализированные модели (pitch-tracking, аудио, парсинг). Настраиваю промпт-инжиниринг для стабильного отклика.",
          tags: ["Claude", "GPT-4o", "LLM", "Audio", "Analytics", "Specialized Models"],
        },
        {
          id: "product-management",
          title: "Управление продуктом",
          subtitle: "Видение и аналитика",
          description:
            "Управляю полным циклом жизни продукта. Отсекаю лишний овердизайн на этапе гипотез, собираю MVP, настраиваю аналитику и итерирую продукт на основе метрик.",
          tags: ["Strategy", "MVP", "Analytics", "Research", "Roadmap"],
        },
      ],
    },
    // Product Modules
    productModules: {
      title: "Модули продуктов",
      openCase: "Открыть кейс",
      visitSite: "Открыть сайт",
      progressLabel: "Прогресс",
      uploadHint: "Загрузить артефакт",
      uploadMore: "Добавить ещё",
      uploadFormats: "PNG, JPG — можно несколько",
      artifactsLabel: "Артефакты",
      artifactPlaceholderTitle: "Макеты скоро",
      artifactPlaceholderHint: "Описание и прогресс кейса уже здесь",
      products: [
        {
          id: "taika",
          number: "001",
          name: "TAIKA",
          type: "AI-платформа для изучения тайского языка",
          status: "В работе / MVP",
          progress: 91,
          link: null,
          tags: ["iOS", "Swift", "AI Lessons", "Speech Recognition", "Thai/Russian", "EdTech"],
          cardDescription: "Персональная AI-учительница тайского языка. Интерактивный курс, голосовая практика, AI-контент и нативный мобильный UX.",
          description: "Персональная AI-учительница тайского языка для русскоязычных пользователей. Курс, голосовая практика, AI-контент, игровые механики и нативный мобильный UX.",
          challenge: "Сделать изучение тайского не академическим, а живым, разговорным и ежедневным.",
          solution: "AI-курс, голосовая практика, игровые упражнения, русско-тайская подача, персональный onboarding.",
          role: "Product, UX/UI, AI logic, content system, iOS prototype.",
          stack: "Swift, iOS, Python, LLM, Speech Recognition.",
          proof: "MVP in progress, full course architecture, onboarding, lesson system, speech practice.",
        },
        {
          id: "hospital-ai",
          number: "002",
          name: "Hospital AI",
          type: "AI-ассистент для медицинского приема",
          status: "Концепт / MVP",
          progress: 42,
          link: null,
          tags: ["Медицина", "AI", "SPA", "Transcription", "PDF Export", "Thailand"],
          cardDescription: "Врачебный интерфейс с записью приема, автоматической расшифровкой и AI-структурированием протокола.",
          description: "Однопользовательский врачебный интерфейс: карточка пациента, запись приема, расшифровка, AI-протокол и PDF. MVP для небольшой клиники в Таиланде.",
          challenge: "Сократить ручное заполнение медицинских протоколов.",
          solution: "Запись речи врача, автоматическая расшифровка, AI-структурирование протокола, PDF.",
          role: "Product scope, UX architecture, interface design, AI workflow.",
          stack: "Web SPA, AI transcription, LLM, PDF export.",
          proof: "Defined MVP scope, 3-4 core screens, business proposal.",
        },
        {
          id: "moo",
          number: "003",
          name: "MOO",
          type: "Сервис подписки на еду",
          status: "Прототип / Web",
          progress: 64,
          link: "https://moo-beryl.vercel.app/",
          tags: ["FoodTech", "Subscription", "Mobile Web", "UX/UI", "Telegram", "Checkout"],
          cardDescription: "Подписка на еду, где рацион собираешь сам: категории, корзина и лёгкий повторный заказ.",
          description: "Мобильный сервис подписки на еду: пользователь сам собирает рацион из категорий и блюд. Простой выбор, понятная корзина, повторный заказ.",
          challenge: "Сделать выбор подписки на еду простым без готовых рационов.",
          solution: "Категории, карусель блюд, подписка, корзина, Telegram welcome flow.",
          role: "Product logic, UX/UI, visual identity, mobile flow.",
          stack: "Web, mobile-first, Telegram, checkout logic.",
          proof: "Visual prototypes, subscription flow, mobile screens.",
        },
        {
          id: "farang",
          number: "004",
          name: "Farang",
          type: "AI-гид для адаптации в Таиланде",
          status: "Концепт / Система",
          progress: 28,
          link: null,
          tags: ["TravelTech", "Relocation", "AI Guide", "Thailand", "Mobile", "Multilingual"],
          cardDescription: "AI-гид для иностранцев в Таиланде: еда, жильё, транспорт, культура и персональные рекомендации.",
          description: "Персональный AI-гид для иностранцев в Таиланде: еда, жилье, транспорт, культура, язык и бонусы. Профиль пользователя и персональные рекомендации.",
          challenge: "Помочь иностранцу быстро разобраться в жизни в Таиланде.",
          solution: "Профили, категории, AI-рекомендации, локальные сценарии.",
          role: "Product concept, UX, onboarding, content architecture.",
          stack: "Mobile app concept, AI assistant, multilingual UX.",
          proof: "Product concept document, user flows, content structure.",
        },
        {
          id: "don-hazza",
          number: "005",
          name: "Don HazzA",
          type: "Платформа для управления ресторанной группой",
          status: "Концепт / Research",
          progress: 15,
          link: null,
          tags: ["FoodTech", "B2B", "Restaurant Management", "Analytics", "Thailand"],
          cardDescription: "Управление сетью ресторанов: меню, заказы, кухня, доставка и аналитика в одной системе.",
          description: "Система управления для сетей ресторанов: меню, заказы, кухня, доставка, аналитика. Фокус на операциях и контроле качества.",
          challenge: "Централизовать управление несколькими ресторанами без потери качества.",
          solution: "Единая система меню, заказов, кухни, доставки и аналитики.",
          role: "Product strategy, B2B UX, operations design.",
          stack: "Web platform, real-time updates, analytics.",
          proof: "Market research, competitor analysis, user interviews.",
        },
        {
          id: "telegram-mini-apps",
          number: "006",
          name: "Telegram Mini Apps",
          type: "Набор мини-приложений для Telegram",
          status: "Эксперименты",
          progress: 35,
          link: null,
          tags: ["Telegram", "Mini Apps", "Bots", "Web3", "Experiments"],
          cardDescription: "Эксперименты в Telegram: игры, утилиты и боты для быстрой валидации идей.",
          description: "Серия экспериментальных мини-приложений в Telegram: игры, утилиты, боты. Быстрое прототипирование и валидация идей.",
          challenge: "Найти product-market fit для Telegram-экосистемы.",
          solution: "Быстрые итерации, A/B тестирование, feedback loop.",
          role: "Product experiments, UX/UI, rapid prototyping.",
          stack: "Telegram Bot API, Web technologies, real-time updates.",
          proof: "Multiple working prototypes, user testing results.",
        },
      ],
    },
    // Process Section
    process: {
      caption: "PROCESS",
      title: "Процесс",
      subtitle: "Большинство людей закрывают один-два этапа. Я собираю всю систему.",
      previousStep: "Предыдущий этап",
      nextStep: "Следующий этап",
      artifactPlaceholderTitle: "Артефакт скоро",
      artifactPlaceholderHint: "Метод и структура этапа — ниже",
      openGallery: "Открыть",
      stages: {
        1: {
          title: "Проблема",
          description: "Формулирую задачу, отделяю симптом от причины, определяю пользователя, контекст и критерии успеха.",
          artifacts: ["Problem Statement", "User Interview", "JTBD", "Hypothesis", "Success Metrics"],
          logic: "Identify → Define → Validate → Measure",
        },
        2: {
          title: "Исследование",
          description: "Собираю данные, изучаю пользователей, рынок, конкурентов и реальные ограничения продукта.",
          artifacts: ["User Interviews", "Competitor Map", "JTBD", "Personas", "Insights"],
          logic: "Observe → Compare → Cluster → Insight",
        },
        3: {
          title: "Продуктовая логика",
          description: "Собираю из хаоса систему: сценарии, MVP scope, приоритеты, метрики и стратегию запуска.",
          artifacts: ["User Journey", "Feature Map", "MVP Scope", "Roadmap", "Metrics"],
          logic: "Structure → Prioritize → Scope → Plan",
        },
        4: {
          title: "UX",
          description: "Проектирую пользовательские сценарии, состояния экранов, навигацию и ключевые точки принятия решений.",
          artifacts: ["User Flow", "Wireframes", "Screen States", "Edge Cases", "Prototype Logic"],
          logic: "Flow → States → Friction → Prototype",
        },
        5: {
          title: "UI",
          description: "Превращаю логику в интерфейс: визуальная система, компоненты, состояния, ритм и читаемость.",
          artifacts: ["Design System", "Components", "Typography", "Spacing", "UI States"],
          logic: "System → Components → States → Polish",
        },
        6: {
          title: "AI-архитектура",
          description: "Проектирую AI-логику: промпты, генерацию контента, структуру данных, автоматизацию и контроль качества.",
          artifacts: ["Prompt System", "LLM Flow", "JSON Structure", "Automation", "QA Logic"],
          logic: "Input → Prompt → Model → Output → Feedback",
        },
        7: {
          title: "Прототип",
          description: "Собираю рабочий прототип, проверяю сценарии, поведение, переходы и ощущение продукта.",
          artifacts: ["Clickable Prototype", "Interaction Map", "Motion States", "Test Build", "Feedback Notes"],
          logic: "Build → Test → Fix → Repeat",
        },
        8: {
          title: "Запуск",
          description: "Довожу продукт до запуска: аналитика, обратная связь, итерации, roadmap и следующая версия.",
          artifacts: ["Launch Plan", "Analytics", "Feedback Loop", "Roadmap", "Iteration Backlog"],
          logic: "Ship → Measure → Learn → Improve",
        },
      },
    },
    // Experience Section
    experience: {
      title: "Опыт",
      intro: "15+ лет в продукте и IT",
      // Companies (Career Path)
      companies: [
        {
          id: "yandex",
          title: "Яндекс",
          startYear: 2018,
          endYear: 2021,
          relevantSkills: ["big-tech", "marketplaces", "web-products", "ai-products"],
          blurb:
            "Крупнейшая IT-компания России — как Google + Amazon: поиск, карты, маркетплейсы, облако и AI для сотен миллионов.",
          role: "Product & UX в big-tech продуктах",
        },
        {
          id: "sber",
          title: "Сбер",
          startYear: 2021,
          endYear: 2022,
          relevantSkills: ["big-tech", "ai-products", "web-products", "mobile"],
          blurb:
            "Экосистема банка и tech — как JPMorgan + Apple Pay / AWS: AI, финтех, облако и digital для миллионов.",
          role: "AI-продукты и digital-сервисы",
        },
        {
          id: "samokat",
          title: "Samokat",
          startYear: 2022,
          endYear: 2025,
          relevantSkills: ["foodtech", "marketplaces", "mobile", "web-products"],
          blurb:
            "Лидер q-commerce — как Getir / DoorDash Instant: доставка за минуты, мобильный продукт и логистика на масштабе.",
          role: "FoodTech и mobile UX",
        },
        {
          id: "independent",
          title: "Independent",
          startYear: 2025,
          endYear: null,
          relevantSkills: ["edtech", "healthcare", "ai-products", "mobile"],
          blurb:
            "Независимая продуктовая практика: AI, EdTech, Healthcare и собственные продукты end-to-end.",
          role: "Самостоятельный product builder",
        },
      ],
      // Skills (Tags and Blocks)
      items: [
        {
          id: "big-tech",
          title: "Big Tech",
          description: "Опыт работы в крупных технологических компаниях с миллионами пользователей. Масштабирование продуктов, работа с большими данными и оптимизация пользовательского опыта.",
          details: "Работал в Яндексе и Сбере, где получил опыт в разработке продуктов для массовой аудитории, управлении сложных системах и работе в кросс-функциональных командах.",
        },
        {
          id: "ecommerce",
          title: "E-commerce",
          description: "Проектирование и оптимизация платформ электронной коммерции. Фокус на конверсии, пользовательском пути и интеграции платежных систем.",
          details: "Опыт в создании и развитии e-commerce решений, включая каталоги товаров, корзину, чекаут и аналитику продаж.",
        },
        {
          id: "marketplaces",
          title: "Marketplaces",
          description: "Разработка двусторонних платформ, где встречаются продавцы и покупатели. Балансирование интересов обеих сторон и создание сетевого эффекта.",
          details: "Работал над маркетплейсами, включая управление продавцами, рейтинги, отзывы и механики вовлечения.",
        },
        {
          id: "foodtech",
          title: "FoodTech",
          description: "Создание продуктов в сфере доставки еды и управления ресторанами. Логистика, интеграция с ресторанами и оптимизация доставки.",
          details: "Опыт в Samokat и других FoodTech проектах. Работал над продуктом для конечных пользователей и B2B решениями для ресторанов.",
        },
        {
          id: "edtech",
          title: "EdTech",
          description: "Проектирование образовательных платформ и систем обучения. Геймификация, прогресс пользователя и адаптивное обучение.",
          details: "Опыт в создании интерактивных курсов, систем отслеживания прогресса и персонализированных путей обучения.",
        },
        {
          id: "healthcare",
          title: "Медицина",
          description: "Разработка медицинских решений и систем управления здравоохранением. Соответствие регуляциям, безопасность данных и удобство для врачей.",
          details: "Работа над системами управления пациентами, электронными медицинскими картами и интеграцией с медицинским оборудованием.",
        },
        {
          id: "ai-products",
          title: "AI продукты",
          description: "Интеграция искусственного интеллекта в потребительские и B2B продукты. Промпт-инженерия, LLM и автоматизация.",
          details: "Опыт в создании AI-ассистентов, систем рекомендаций, автоматизации контента и интеграции современных LLM.",
        },
        {
          id: "mobile",
          title: "Мобильные приложения",
          description: "Разработка нативных и кросс-платформенных мобильных приложений. iOS, Android, UX для мобиля и оптимизация производительности.",
          details: "Опыт в Swift, Kotlin и кросс-платформенных фреймворках. Работа над приложениями с миллионами установок.",
        },
        {
          id: "web-products",
          title: "Web продукты",
          description: "Создание веб-приложений и SPA. React, Vue, TypeScript и современный веб-стек. Оптимизация производительности и SEO.",
          details: "Опыт в создании сложных веб-приложений, от простых лендингов до полнофункциональных платформ с реал-тайм обновлениями.",
        },
      ],
      timeline: "Yandex → Sber → Samokat → Independent Product Builder",
    },
    // Now Building Section
    nowBuilding: {
      title: "Сейчас создаю",
      projects: [
        {
          id: "taika",
          name: "TAIKA",
          progress: 91,
          status: "MVP in progress",
          description: "Персональная AI-учительница тайского языка для русскоязычных пользователей.",
          details: "Платформа объединяет интерактивный курс, голосовую практику, AI-контент, игровые механики и нативный мобильный UX. Фокус на разговорном языке и ежедневной практике.",
        },
        {
          id: "hospital-ai",
          name: "Hospital AI",
          progress: 42,
          status: "MVP scope",
          description: "AI-ассистент для медицинского приема и документирования.",
          details: "Врачебный интерфейс с записью приема, автоматической расшифровкой, AI-структурированием протокола и экспортом PDF. Разработан для небольших клиник в Таиланде.",
        },
        {
          id: "moo",
          name: "MOO",
          progress: 64,
          status: "Prototype",
          description: "Сервис подписки на еду с персональным составлением рациона.",
          details: "Мобильный сервис, где пользователь сам собирает рацион из доступных категорий и блюд. Фокус на простом выборе, понятной корзине и легком повторном заказе.",
        },
        {
          id: "new-product",
          name: "New product",
          progress: 0,
          status: "Research",
          description: "Новый продукт на этапе исследования и валидации.",
          details: "Находится на этапе глубокого исследования рынка, интервью с пользователями и формирования MVP scope. Скоро будут обновления.",
        },
        {
          id: "secret",
          name: "Secret",
          progress: 0,
          status: "Coming soon",
          description: "Секретный проект, над которым ведется работа.",
          details: "Детали будут раскрыты позже. Следите за обновлениями в социальных сетях и Telegram.",
        },
      ],
    },
    // Contact Section
    contact: {
      title: "Давайте создавать.",
      links: {
        telegram: "https://t.me/bayshev",
        instagram: "https://instagram.com/bayshev",
        email: "mailto:sabaishev@icloud.com",
      },
      labels: {
        telegram: "Telegram",
        instagram: "Instagram",
        email: "Email",
      },
      form: {
        subtitle: "Собери бриф за минуту — только тапы и слайдер, без ручного ввода.",
        briefLabel: "Brief",
        next: "Дальше",
        submit: "Отправить бриф",
        sent: "Открыто",
        submitSubject: "Бриф · VIKTOR.SYSTEM",
        submitMessage: "Привет! Хочу обсудить проект.",
        summaryTitle: "Сводка",
        steps: {
          need: "Что нужно",
          domain: "Сфера",
          budget: "Бюджет",
          location: "Локация",
          timeline: "Сроки",
          channel: "Связь",
        },
        hints: {
          need: "Можно отметить несколько.",
          domain: "Можно отметить несколько — всё, что близко к задаче.",
          budget: "Потяни слайдер. Валюта — одним тапом.",
          location: "Где будет жить продукт.",
          timeline: "Когда хочешь стартовать.",
          channel: "Куда отправить бриф.",
        },
        summary: {
          need: "Нужно",
          domain: "Сфера",
          budget: "Бюджет",
          location: "Локация",
          timeline: "Сроки",
          channel: "Связь",
        },
        currencies: {
          RUB: "₽ Рубли",
          THB: "฿ Баты",
          USD: "$ Доллары",
        },
        options: {
          need: [
            { id: "mvp", label: "MVP / прототип" },
            { id: "product", label: "Продукт с нуля" },
            { id: "redesign", label: "Редизайн" },
            { id: "ai", label: "AI-фича" },
            { id: "mobile", label: "Мобильное приложение" },
            { id: "web", label: "Web-продукт" },
            { id: "telegram-bot", label: "Telegram-бот" },
            { id: "workspace", label: "Workspace / внутренний инструмент" },
            { id: "automation", label: "Автоматизация" },
            { id: "audit", label: "Аудит / консультация" },
          ],
          domain: [
            { id: "fintech", label: "FinTech" },
            { id: "foodtech", label: "FoodTech" },
            { id: "edtech", label: "EdTech" },
            { id: "health", label: "Healthcare" },
            { id: "ecommerce", label: "E-commerce" },
            { id: "marketplace", label: "Marketplace" },
            { id: "saas", label: "SaaS / B2B" },
            { id: "telegram", label: "Telegram / боты" },
            { id: "workspace", label: "Workspace / productivity" },
            { id: "ai-tools", label: "AI-инструменты" },
            { id: "media", label: "Media / контент" },
            { id: "travel", label: "Travel / hospitality" },
            { id: "realestate", label: "Real Estate" },
            { id: "logistics", label: "Logistics" },
            { id: "hr", label: "HR / recruiting" },
            { id: "gaming", label: "Gaming / entertainment" },
            { id: "crypto", label: "Crypto / Web3" },
            { id: "other", label: "Другое" },
          ],
          location: [
            { id: "ru", label: "Россия" },
            { id: "th", label: "Таиланд" },
            { id: "sea", label: "SEA / Азия" },
            { id: "eu", label: "Европа" },
            { id: "us", label: "США" },
            { id: "global", label: "Глобально" },
            { id: "remote", label: "Remote" },
          ],
          timeline: [
            { id: "asap", label: "Как можно скорее" },
            { id: "1m", label: "В течение месяца" },
            { id: "1-3m", label: "1–3 месяца" },
            { id: "3m+", label: "3+ месяца" },
            { id: "explore", label: "Пока исследую" },
          ],
          channel: [
            { id: "telegram", label: "Telegram" },
            { id: "email", label: "Email" },
            { id: "instagram", label: "Instagram" },
          ],
        },
      },
      footer: {
        tagline: "AI Product Builder. От идеи и UX до запуска.",
        navTitle: "Навигация",
        contactTitle: "Контакты",
        rights: "Все права защищены.",
        built: "Built as a personal OS.",
      },
    },
    // SEO
    seo: {
      title: "VIKTOR.SYSTEM — AI Product Builder",
      description: "Персональная система проектов Виктора: AI, UX/UI, mobile, web, automation and product strategy.",
    },
  },

  en: {
    // Header
    header: {
      title: "VIKTOR.SYSTEM",
      status: "Online",
      messages: [
        "Available for a new project",
        "I'll ship your MVP end-to-end",
        "Product · UX · AI in one",
        "Leave a brief below",
        "I reply today",
      ],
    },
    // Boot Screen
    boot: {
      title: "VIKTOR.SYSTEM",
      line: "products you want to open",
      sequence: [
        "Boot sequence...",
        "Loading modules...",
        "AI loaded",
        "Product loaded",
        "Design loaded",
        "Strategy loaded",
        "Automation loaded",
        "System ready",
      ],
    },
    // Hero Section
    hero: {
      title: "I build products.",
      subtitle: "From idea and UX to AI, automation and launch.",
      tags: ["Product", "UX/UI", "AI", "Mobile", "Web", "Automation"],
      quickLinks: [
        { label: "Product", stage: 3 },
        { label: "UX/UI", stage: 4 },
        { label: "AI", stage: 6 },
        { label: "Mobile", stage: 7 },
        { label: "Web", stage: 5 },
        { label: "Automation", stage: 8 },
      ],
      cta: {
        explore: "View products",
        contact: "Get in touch",
      },
    },
    stackCapabilities: {
      title: "The Stack & Capabilities",
      subtitle: "Technical arsenal and tools for the full development cycle",
      cards: [
        {
          id: "design-to-code",
          title: "Design to Code",
          subtitle: "Figma → Xcode",
          description:
            "I design UI/UX in Figma with SwiftUI/UIKit constraints in mind. Components, styles and auto-layouts transfer into Xcode one-to-one — no lost logic, no lost pixels. Strict architecture from concept to native code.",
          tags: ["Figma", "Xcode", "SwiftUI", "UIKit", "Design Systems"],
        },
        {
          id: "supercharged-dev",
          title: "Super-charged Development",
          subtitle: "Cursor IDE + AI",
          description:
            "I run Cursor IDE on steroids. Custom .cursorrules tuned to my projects so the AI assistant ships clean, typed code on the first pass — without hallucinations. It replaces a small development team.",
          tags: ["Cursor IDE", "Claude", "GPT-4", "Code Generation"],
        },
        {
          id: "ai-integration",
          title: "AI Integration",
          subtitle: "Models & Agents",
          description:
            "I embed AI for specific UI and logic jobs. I combine engines: Claude 3.5 Sonnet for complex code, GPT-4o for data analytics, plus specialized models (pitch-tracking, audio, parsing). Prompt engineering for stable responses.",
          tags: ["Claude", "GPT-4o", "LLM", "Audio Processing", "Data Analytics", "Specialized Models"],
        },
        {
          id: "product-management",
          title: "Product Management",
          subtitle: "Vision & Analytics",
          description:
            "I own the full product lifecycle. Cut overdesign at the hypothesis stage, ship MVP, wire analytics, and iterate from metrics.",
          tags: ["Product Strategy", "MVP", "Analytics", "User Research", "Roadmapping"],
        },
      ],
    },
    // Product Modules
    productModules: {
      title: "Product modules",
      openCase: "Open case",
      visitSite: "Visit site",
      progressLabel: "Progress",
      uploadHint: "Upload artifact",
      uploadMore: "Add more",
      uploadFormats: "PNG, JPG — multiple files",
      artifactsLabel: "Artifacts",
      artifactPlaceholderTitle: "Screens coming soon",
      artifactPlaceholderHint: "Case description and progress are already here",
      products: [
        {
          id: "taika",
          number: "001",
          name: "TAIKA",
          type: "AI language learning platform",
          status: "In progress / MVP",
          progress: 91,
          link: null,
          tags: ["iOS", "Swift", "AI Lessons", "Speech Recognition", "Thai/Russian", "EdTech"],
          cardDescription: "Personal AI Thai teacher. Interactive course, voice practice, AI content and native mobile UX.",
          description: "Personal AI Thai language teacher for Russian speakers. Course, voice practice, AI content, game mechanics and native mobile UX.",
          challenge: "Make Thai learning not academic but conversational, alive and daily.",
          solution: "AI course, voice practice, game exercises, Russian-Thai presentation, personalized onboarding.",
          role: "Product, UX/UI, AI logic, content system, iOS prototype.",
          stack: "Swift, iOS, Python, LLM, Speech Recognition.",
          proof: "MVP in progress, full course architecture, onboarding, lesson system, speech practice.",
        },
        {
          id: "hospital-ai",
          number: "002",
          name: "Hospital AI",
          type: "AI assistant for medical appointments",
          status: "Concept / MVP scope",
          progress: 42,
          link: null,
          tags: ["Healthcare", "AI", "SPA", "Transcription", "PDF Export", "Thailand"],
          cardDescription: "Doctor interface with appointment recording, auto transcription and AI-structured protocol.",
          description: "Single-user doctor interface: patient card, appointment recording, transcription, AI protocol and PDF. MVP for a small clinic in Thailand.",
          challenge: "Reduce manual medical protocol filling.",
          solution: "Doctor voice recording, automatic transcription, AI protocol structuring, PDF.",
          role: "Product scope, UX architecture, interface design, AI workflow.",
          stack: "Web SPA, AI transcription, LLM, PDF export.",
          proof: "Defined MVP scope, 3-4 core screens, business proposal.",
        },
        {
          id: "moo",
          number: "003",
          name: "MOO",
          type: "Food subscription service",
          status: "Prototype / Web concept",
          progress: 64,
          link: "https://moo-beryl.vercel.app/",
          tags: ["FoodTech", "Subscription", "Mobile Web", "UX/UI", "Telegram", "Checkout"],
          cardDescription: "Food subscription where you build your own diet: categories, cart and easy reordering.",
          description: "Mobile food subscription where users build their own diet from categories and dishes. Simple selection, clear cart, easy reordering.",
          challenge: "Make food subscription choice simple without preset diets.",
          solution: "Categories, dish carousel, subscription, cart, Telegram welcome flow.",
          role: "Product logic, UX/UI, visual identity, mobile flow.",
          stack: "Web, mobile-first, Telegram, checkout logic.",
          proof: "Visual prototypes, subscription flow, mobile screens.",
        },
        {
          id: "farang",
          number: "004",
          name: "Farang",
          type: "AI guide for adaptation in Thailand",
          status: "Concept / Product system",
          progress: 28,
          link: null,
          tags: ["TravelTech", "Relocation", "AI Guide", "Thailand", "Mobile", "Multilingual"],
          cardDescription: "AI guide for foreigners in Thailand: food, housing, transport, culture and personal recommendations.",
          description: "Personal AI guide for foreigners in Thailand: food, housing, transport, culture, language and bonuses. User profile and personalized recommendations.",
          challenge: "Help foreigner quickly understand life in Thailand.",
          solution: "Profiles, categories, AI recommendations, local scenarios.",
          role: "Product concept, UX, onboarding, content architecture.",
          stack: "Mobile app concept, AI assistant, multilingual UX.",
          proof: "Product concept document, user flows, content structure.",
        },
        {
          id: "don-hazza",
          number: "005",
          name: "Don HazzA",
          type: "Restaurant group management platform",
          status: "Concept / Research",
          progress: 15,
          link: null,
          tags: ["FoodTech", "B2B", "Restaurant Management", "Analytics", "Thailand"],
          cardDescription: "Restaurant chain ops: menu, orders, kitchen, delivery and analytics in one system.",
          description: "Management system for restaurant chains: menu, orders, kitchen, delivery, analytics. Focus on operations and quality control.",
          challenge: "Centralize management of multiple restaurants without losing quality.",
          solution: "Unified system for menu, orders, kitchen, delivery and analytics.",
          role: "Product strategy, B2B UX, operations design.",
          stack: "Web platform, real-time updates, analytics.",
          proof: "Market research, competitor analysis, user interviews.",
        },
        {
          id: "telegram-mini-apps",
          number: "006",
          name: "Telegram Mini Apps",
          type: "Set of mini apps for Telegram",
          status: "Experiments / In progress",
          progress: 35,
          link: null,
          tags: ["Telegram", "Mini Apps", "Bots", "Web3", "Experiments"],
          cardDescription: "Telegram experiments: games, utilities and bots for fast idea validation.",
          description: "Series of experimental mini apps in Telegram: games, utilities, bots. Rapid prototyping and idea validation.",
          challenge: "Find product-market fit for Telegram ecosystem.",
          solution: "Fast iterations, A/B testing, feedback loop.",
          role: "Product experiments, UX/UI, rapid prototyping.",
          stack: "Telegram Bot API, Web technologies, real-time updates.",
          proof: "Multiple working prototypes, user testing results.",
        },
      ],
    },
    // Process Section
    process: {
      caption: "PROCESS",
      title: "Process",
      subtitle: "Most people close one or two stages. I build the whole system.",
      previousStep: "Previous step",
      nextStep: "Next step",
      artifactPlaceholderTitle: "Artifact coming soon",
      artifactPlaceholderHint: "Method and stage structure are below",
      openGallery: "Open",
      stages: {
        1: {
          title: "Problem",
          description: "I formulate the task, separate symptom from cause, identify user, context and success criteria.",
          artifacts: ["Problem Statement", "User Interview", "JTBD", "Hypothesis", "Success Metrics"],
          logic: "Identify → Define → Validate → Measure",
        },
        2: {
          title: "Research",
          description: "I gather data, study users, market, competitors and real product constraints.",
          artifacts: ["User Interviews", "Competitor Map", "JTBD", "Personas", "Insights"],
          logic: "Observe → Compare → Cluster → Insight",
        },
        3: {
          title: "Product logic",
          description: "I build system from chaos: scenarios, MVP scope, priorities, metrics and launch strategy.",
          artifacts: ["User Journey", "Feature Map", "MVP Scope", "Roadmap", "Metrics"],
          logic: "Structure → Prioritize → Scope → Plan",
        },
        4: {
          title: "UX",
          description: "I design user scenarios, screen states, navigation and key decision points.",
          artifacts: ["User Flow", "Wireframes", "Screen States", "Edge Cases", "Prototype Logic"],
          logic: "Flow → States → Friction → Prototype",
        },
        5: {
          title: "UI",
          description: "I turn logic into interface: visual system, components, states, rhythm and readability.",
          artifacts: ["Design System", "Components", "Typography", "Spacing", "UI States"],
          logic: "System → Components → States → Polish",
        },
        6: {
          title: "AI architecture",
          description: "I design AI logic: prompts, content generation, data structure, automation and quality control.",
          artifacts: ["Prompt System", "LLM Flow", "JSON Structure", "Automation", "QA Logic"],
          logic: "Input → Prompt → Model → Output → Feedback",
        },
        7: {
          title: "Prototype",
          description: "I build working prototype, test scenarios, behavior, transitions and product feel.",
          artifacts: ["Clickable Prototype", "Interaction Map", "Motion States", "Test Build", "Feedback Notes"],
          logic: "Build → Test → Fix → Repeat",
        },
        8: {
          title: "Launch",
          description: "I bring product to launch: analytics, feedback, iterations, roadmap and next version.",
          artifacts: ["Launch Plan", "Analytics", "Feedback Loop", "Roadmap", "Iteration Backlog"],
          logic: "Ship → Measure → Learn → Improve",
        },
      },
    },
    // Experience Section
    experience: {
      title: "Experience",
      intro: "15+ years in Product & IT",
      companies: [
        {
          id: "yandex",
          title: "Yandex",
          startYear: 2018,
          endYear: 2021,
          relevantSkills: ["big-tech", "marketplaces", "web-products", "ai-products"],
          blurb:
            "Think Google + Amazon for Russia — search, maps, marketplaces, cloud and AI used by hundreds of millions.",
          role: "Product & UX in big-tech products",
        },
        {
          id: "sber",
          title: "Sber",
          startYear: 2021,
          endYear: 2022,
          relevantSkills: ["big-tech", "ai-products", "web-products", "mobile"],
          blurb:
            "Like JPMorgan meets Apple Pay / AWS — a banking + tech ecosystem with AI, fintech and digital services for millions.",
          role: "AI products & digital services",
        },
        {
          id: "samokat",
          title: "Samokat",
          startYear: 2022,
          endYear: 2025,
          relevantSkills: ["foodtech", "marketplaces", "mobile", "web-products"],
          blurb:
            "Russia's Getir / DoorDash Instant — ultra-fast grocery delivery, mobile product and logistics at city scale.",
          role: "FoodTech product & mobile UX",
        },
        {
          id: "independent",
          title: "Independent",
          startYear: 2025,
          endYear: null,
          relevantSkills: ["edtech", "healthcare", "ai-products", "mobile"],
          blurb:
            "Independent product practice — AI, EdTech, Healthcare and end-to-end product building as a solo system.",
          role: "Solo product builder",
        },
      ],
      items: [
        {
          id: "big-tech",
          title: "Big Tech",
          description: "Experience working at large tech companies with millions of users. Scaling products, working with big data and optimizing user experience.",
          details: "Worked at Yandex and Sber, gaining experience in developing products for mass audiences, managing complex systems and working in cross-functional teams.",
        },
        {
          id: "ecommerce",
          title: "E-commerce",
          description: "Designing and optimizing e-commerce platforms. Focus on conversion, user journey and payment integration.",
          details: "Experience in creating and developing e-commerce solutions, including product catalogs, shopping cart, checkout and sales analytics.",
        },
        {
          id: "marketplaces",
          title: "Marketplaces",
          description: "Developing two-sided platforms where sellers and buyers meet. Balancing interests of both sides and creating network effects.",
          details: "Worked on marketplaces, including seller management, ratings, reviews and engagement mechanics.",
        },
        {
          id: "foodtech",
          title: "FoodTech",
          description: "Creating products in food delivery and restaurant management. Logistics, restaurant integration and delivery optimization.",
          details: "Experience at Samokat and other FoodTech projects. Worked on both consumer and B2B restaurant solutions.",
        },
        {
          id: "edtech",
          title: "EdTech",
          description: "Designing educational platforms and learning systems. Gamification, user progress and adaptive learning.",
          details: "Creating interactive courses, progress tracking systems and personalized learning paths.",
        },
        {
          id: "healthcare",
          title: "Healthcare",
          description: "Developing medical solutions and healthcare management systems. Compliance, data security and doctor convenience.",
          details: "Work on patient management systems, electronic medical records and medical equipment integration.",
        },
        {
          id: "ai-products",
          title: "AI products",
          description: "Integrating artificial intelligence into consumer and B2B products. Prompt engineering, LLMs and automation.",
          details: "Experience in creating AI assistants, recommendation systems, content automation and modern LLM integration.",
        },
        {
          id: "mobile",
          title: "Mobile apps",
          description: "Developing native and cross-platform mobile applications. iOS, Android, mobile UX and performance optimization.",
          details: "Experience with Swift, Kotlin and cross-platform frameworks. Worked on apps with millions of installs.",
        },
        {
          id: "web-products",
          title: "Web products",
          description: "Creating web applications and SPAs. React, Vue, TypeScript and modern web stack. Performance and SEO optimization.",
          details: "Experience in creating complex web applications, from simple landing pages to full-featured platforms with real-time updates.",
        },
      ],
      timeline: "Yandex → Sber → Samokat → Independent Product Builder",
    },
    // Now Building Section
    nowBuilding: {
      title: "Now building",
      projects: [
        {
          id: "taika",
          name: "TAIKA",
          progress: 91,
          status: "MVP in progress",
          description: "Personal AI Thai language teacher for Russian speakers.",
          details: "Platform combines interactive course, voice practice, AI content, game mechanics and native mobile UX. Focus on conversational language and daily practice.",
        },
        {
          id: "hospital-ai",
          name: "Hospital AI",
          progress: 42,
          status: "MVP scope",
          description: "AI assistant for medical appointments and documentation.",
          details: "Doctor interface with appointment recording, automatic transcription, AI-structured protocol and PDF export. Developed for small clinics in Thailand.",
        },
        {
          id: "moo",
          name: "MOO",
          progress: 64,
          status: "Prototype",
          description: "Food subscription service with personalized diet composition.",
          details: "Mobile service where users build their own diet from available categories and dishes. Focus on simple selection, clear cart and easy reordering.",
        },
        {
          id: "new-product",
          name: "New product",
          progress: 0,
          status: "Research",
          description: "New product at research and validation stage.",
          details: "Currently at deep market research, user interviews and MVP scope formation. Updates coming soon.",
        },
        {
          id: "secret",
          name: "Secret",
          progress: 0,
          status: "Coming soon",
          description: "Secret project in development.",
          details: "Details will be revealed later. Follow updates on social media and Telegram.",
        },
      ],
    },
    // Contact Section
    contact: {
      title: "Let's build.",
      links: {
        telegram: "https://t.me/bayshev",
        instagram: "https://instagram.com/bayshev",
        email: "mailto:sabaishev@icloud.com",
      },
      labels: {
        telegram: "Telegram",
        instagram: "Instagram",
        email: "Email",
      },
      form: {
        subtitle: "Build a brief in a minute — taps and a slider only. No typing.",
        briefLabel: "Brief",
        next: "Next",
        submit: "Send brief",
        sent: "Opened",
        submitSubject: "Brief · VIKTOR.SYSTEM",
        submitMessage: "Hi! I'd like to discuss a project.",
        summaryTitle: "Summary",
        steps: {
          need: "What you need",
          domain: "Domain",
          budget: "Budget",
          location: "Location",
          timeline: "Timeline",
          channel: "Contact",
        },
        hints: {
          need: "Pick one or more.",
          domain: "Pick one or more — everything close to the job.",
          budget: "Drag the slider. Currency in one tap.",
          location: "Where the product will live.",
          timeline: "When you want to start.",
          channel: "Where to send the brief.",
        },
        summary: {
          need: "Need",
          domain: "Domain",
          budget: "Budget",
          location: "Location",
          timeline: "Timeline",
          channel: "Contact",
        },
        currencies: {
          RUB: "₽ RUB",
          THB: "฿ THB",
          USD: "$ USD",
        },
        options: {
          need: [
            { id: "mvp", label: "MVP / prototype" },
            { id: "product", label: "Product from scratch" },
            { id: "redesign", label: "Redesign" },
            { id: "ai", label: "AI feature" },
            { id: "mobile", label: "Mobile app" },
            { id: "web", label: "Web product" },
            { id: "telegram-bot", label: "Telegram bot" },
            { id: "workspace", label: "Workspace / internal tool" },
            { id: "automation", label: "Automation" },
            { id: "audit", label: "Audit / consult" },
          ],
          domain: [
            { id: "fintech", label: "FinTech" },
            { id: "foodtech", label: "FoodTech" },
            { id: "edtech", label: "EdTech" },
            { id: "health", label: "Healthcare" },
            { id: "ecommerce", label: "E-commerce" },
            { id: "marketplace", label: "Marketplace" },
            { id: "saas", label: "SaaS / B2B" },
            { id: "telegram", label: "Telegram / bots" },
            { id: "workspace", label: "Workspace / productivity" },
            { id: "ai-tools", label: "AI tools" },
            { id: "media", label: "Media / content" },
            { id: "travel", label: "Travel / hospitality" },
            { id: "realestate", label: "Real Estate" },
            { id: "logistics", label: "Logistics" },
            { id: "hr", label: "HR / recruiting" },
            { id: "gaming", label: "Gaming / entertainment" },
            { id: "crypto", label: "Crypto / Web3" },
            { id: "other", label: "Other" },
          ],
          location: [
            { id: "ru", label: "Russia" },
            { id: "th", label: "Thailand" },
            { id: "sea", label: "SEA / Asia" },
            { id: "eu", label: "Europe" },
            { id: "us", label: "USA" },
            { id: "global", label: "Global" },
            { id: "remote", label: "Remote" },
          ],
          timeline: [
            { id: "asap", label: "ASAP" },
            { id: "1m", label: "Within a month" },
            { id: "1-3m", label: "1–3 months" },
            { id: "3m+", label: "3+ months" },
            { id: "explore", label: "Just exploring" },
          ],
          channel: [
            { id: "telegram", label: "Telegram" },
            { id: "email", label: "Email" },
            { id: "instagram", label: "Instagram" },
          ],
        },
      },
      footer: {
        tagline: "AI Product Builder. From idea and UX to launch.",
        navTitle: "Navigate",
        contactTitle: "Contact",
        rights: "All rights reserved.",
        built: "Built as a personal OS.",
      },
    },
    // SEO
    seo: {
      title: "VIKTOR.SYSTEM — AI Product Builder",
      description: "Viktor's personal project system: AI, UX/UI, mobile, web, automation and product strategy.",
    },
  },

  th: {
    // Header
    header: {
      title: "VIKTOR.SYSTEM",
      status: "Online",
      messages: [
        "ว่างรับโปรเจกต์ใหม่",
        "ทำ MVP ให้ครบวงจร",
        "Product · UX · AI ในที่เดียว",
        "ทิ้งบรีฟด้านล่างได้",
        "ตอบกลับวันนี้",
      ],
    },
    // Boot Screen
    boot: {
      title: "VIKTOR.SYSTEM",
      line: "ผลิตภัณฑ์ที่อยากเปิดดู",
      sequence: [
        "Boot sequence...",
        "Loading modules...",
        "AI loaded",
        "Product loaded",
        "Design loaded",
        "Strategy loaded",
        "Automation loaded",
        "System ready",
      ],
    },
    // Hero Section
    hero: {
      title: "ฉันสร้างผลิตภัณฑ์",
      subtitle: "จากแนวคิดและ UX ไปจนถึง AI การทำให้เป็นอัตโนมัติและการเปิดตัว",
      tags: ["Product", "UX/UI", "AI", "Mobile", "Web", "Automation"],
      quickLinks: [
        { label: "Product", stage: 3 },
        { label: "UX/UI", stage: 4 },
        { label: "AI", stage: 6 },
        { label: "Mobile", stage: 7 },
        { label: "Web", stage: 5 },
        { label: "Automation", stage: 8 },
      ],
      cta: {
        explore: "ดูผลิตภัณฑ์",
        contact: "ติดต่อ",
      },
    },
    stackCapabilities: {
      title: "สแต็กและความสามารถ",
      subtitle: "คลังเครื่องมือและเทคโนโลยีสำหรับวงจรการพัฒนาแบบครบวงจร",
      cards: [
        {
          id: "design-to-code",
          title: "Design to Code",
          subtitle: "Figma → Xcode",
          description:
            "ออกแบบ UI/UX ใน Figma โดยคำนึงถึงข้อจำกัดของ SwiftUI/UIKit คอมโพเนนต์ สไตล์ และออโต้เลย์เอาต์ย้ายไป Xcode แบบหนึ่งต่อหนึ่ง โดยไม่สูญเสียตรรกะและพิกเซล",
          tags: ["Figma", "Xcode", "SwiftUI", "UIKit", "Design Systems"],
        },
        {
          id: "supercharged-dev",
          title: "Super-charged Development",
          subtitle: "Cursor IDE + AI",
          description:
            "ใช้ Cursor IDE แบบเต็มกำลัง พร้อม .cursorrules ที่ปรับแต่งเอง เพื่อให้ AI สร้างโค้ดที่สะอาดและมี type ตั้งแต่ครั้งแรก — แทนทีมพัฒนาขนาดเล็ก",
          tags: ["Cursor IDE", "Claude", "GPT-4", "Code Generation"],
        },
        {
          id: "ai-integration",
          title: "AI Integration",
          subtitle: "Models & Agents",
          description:
            "ฝัง AI ตามงาน UI และลอจิกจริง รวมเอนจิน: Claude 3.5 Sonnet สำหรับโค้ดซับซ้อน, GPT-4o สำหรับวิเคราะห์ข้อมูล และโมเดลเฉพาะทาง พร้อม prompt engineering ที่เสถียร",
          tags: ["Claude", "GPT-4o", "LLM", "Audio Processing", "Data Analytics", "Specialized Models"],
        },
        {
          id: "product-management",
          title: "Product Management",
          subtitle: "Vision & Analytics",
          description:
            "ดูแลวงจรชีวิตผลิตภัณฑ์ทั้งหมด ตัด overdesign ตั้งแต่สมมติฐาน สร้าง MVP ตั้งค่า analytics และวนซ้ำจากเมตริก",
          tags: ["Product Strategy", "MVP", "Analytics", "User Research", "Roadmapping"],
        },
      ],
    },
    // Legacy (keep for backward compatibility)
    systemStatus: {
      title: "Track Record",
      metrics: [
        { value: "15+", label: "ปีในผลิตภัณฑ์และเทคโนโลยี" },
        { value: "12+", label: "ผลิตภัณฑ์และแนวคิด" },
        { value: "4+", label: "อุตสาหกรรม" },
        { value: "3", label: "ภาษา" },
        { value: "∞", label: "ไอเดียที่อยู่ระหว่างดำเนินการ" },
      ],
    },
    // Product Modules
    productModules: {
      title: "โมดูลผลิตภัณฑ์",
      openCase: "เปิดเคส",
      visitSite: "เปิดเว็บไซต์",
      progressLabel: "ความคืบหน้า",
      uploadHint: "อัปโหลดอาร์ติแฟกต์",
      uploadMore: "เพิ่มอีก",
      uploadFormats: "PNG, JPG — หลายไฟล์ได้",
      artifactsLabel: "อาร์ติแฟกต์",
      artifactPlaceholderTitle: "มาเร็ว ๆ นี้",
      artifactPlaceholderHint: "มีรายละเอียดและความคืบหน้าของเคสแล้ว",
      products: [
        {
          id: "taika",
          number: "001",
          name: "TAIKA",
          type: "แพลตฟอร์ม AI สำหรับการเรียนรู้ภาษาไทย",
          status: "กำลังพัฒนา / MVP",
          progress: 91,
          link: null,
          tags: ["iOS", "Swift", "AI Lessons", "Speech Recognition", "Thai/Russian", "EdTech"],
          cardDescription: "ครูสอนภาษาไทย AI ส่วนบุคคล หลักสูตร การฝึกเสียง เนื้อหา AI และ UX มือถือ",
          description: "ครูสอนภาษาไทย AI ส่วนบุคคลสำหรับผู้พูดภาษารัสเซีย หลักสูตร การฝึกเสียง เนื้อหา AI กลไกเกม และ UX มือถือ",
          challenge: "ทำให้การเรียนรู้ภาษาไทยไม่ใช่วิชาการ แต่เป็นการสนทนาที่มีชีวิตและเป็นประจำวัน",
          solution: "AI-คอร์ส การฝึกเสียง แบบฝึกหัดเกม การนำเสนอแบบรัสเซีย-ไทย การเข้าเรียนส่วนบุคคล",
          role: "Product, UX/UI, AI logic, content system, iOS prototype.",
          stack: "Swift, iOS, Python, LLM, Speech Recognition.",
          proof: "MVP in progress, full course architecture, onboarding, lesson system, speech practice.",
        },
        {
          id: "hospital-ai",
          number: "002",
          name: "Hospital AI",
          type: "ผู้ช่วย AI สำหรับการนัดหมายแพทย์",
          status: "แนวคิด / MVP",
          progress: 42,
          link: null,
          tags: ["Healthcare", "AI", "SPA", "Transcription", "PDF Export", "Thailand"],
          cardDescription: "อินเตอร์เฟซแพทย์พร้อมบันทึกนัดหมาย ถอดเสียงอัตโนมัติ และโปรโตคอล AI",
          description: "อินเตอร์เฟซแพทย์: บัตรผู้ป่วย บันทึกนัดหมาย ถอดเสียง โปรโตคอล AI และ PDF สำหรับคลินิกเล็กในไทย",
          challenge: "ลดการกรอกโปรโตคอลทางการแพทย์ด้วยตนเอง",
          solution: "การบันทึกเสียงแพทย์ การถอดเสียงอัตโนมัติ การจัดโครงสร้างโปรโตคอล AI PDF",
          role: "Product scope, UX architecture, interface design, AI workflow.",
          stack: "Web SPA, AI transcription, LLM, PDF export.",
          proof: "Defined MVP scope, 3-4 core screens, business proposal.",
        },
        {
          id: "moo",
          number: "003",
          name: "MOO",
          type: "บริการสมัครสมาชิกอาหาร",
          status: "ต้นแบบ / Web",
          progress: 64,
          link: "https://moo-beryl.vercel.app/",
          tags: ["FoodTech", "Subscription", "Mobile Web", "UX/UI", "Telegram", "Checkout"],
          cardDescription: "สมัครสมาชิกอาหารที่สร้างเมนูเอง: หมวดหมู่ ตะกร้า และสั่งซ้ำง่าย",
          description: "บริการสมัครสมาชิกอาหารบนมือถือ ผู้ใช้สร้างอาหารเองจากหมวดหมู่และจาน เลือกง่าย ตะกร้าชัด สั่งซ้ำง่าย",
          challenge: "ทำให้การเลือกสมัครสมาชิกอาหารง่ายขึ้นโดยไม่มีอาหารที่กำหนดไว้ล่วงหน้า",
          solution: "หมวดหมู่ คาร์ูเซลจาน สมัครสมาชิก ตะกร้า Telegram ต้อนรับการไหล",
          role: "Product logic, UX/UI, visual identity, mobile flow.",
          stack: "Web, mobile-first, Telegram, checkout logic.",
          proof: "Visual prototypes, subscription flow, mobile screens.",
        },
        {
          id: "farang",
          number: "004",
          name: "Farang",
          type: "ไกด์ AI สำหรับการปรับตัวในประเทศไทย",
          status: "แนวคิด / ระบบ",
          progress: 28,
          link: null,
          tags: ["TravelTech", "Relocation", "AI Guide", "Thailand", "Mobile", "Multilingual"],
          cardDescription: "ไกด์ AI สำหรับชาวต่างชาติในไทย: อาหาร ที่อยู่ ขนส่ง วัฒนธรรม และคำแนะนำ",
          description: "ไกด์ AI ส่วนบุคคลสำหรับชาวต่างชาติในไทย: อาหาร ที่อยู่ ขนส่ง วัฒนธรรม ภาษา และโบนัส",
          challenge: "ช่วยชาวต่างชาติให้เข้าใจชีวิตในประเทศไทยได้อย่างรวดเร็ว",
          solution: "โปรไฟล์ หมวดหมู่ คำแนะนำ AI สถานการณ์ท้องถิ่น",
          role: "Product concept, UX, onboarding, content architecture.",
          stack: "Mobile app concept, AI assistant, multilingual UX.",
          proof: "Product concept document, user flows, content structure.",
        },
        {
          id: "don-hazza",
          number: "005",
          name: "Don HazzA",
          type: "แพลตฟอร์มการจัดการกลุ่มร้านอาหาร",
          status: "แนวคิด / วิจัย",
          progress: 15,
          link: null,
          tags: ["FoodTech", "B2B", "Restaurant Management", "Analytics", "Thailand"],
          cardDescription: "จัดการเครือร้านอาหาร: เมนู คำสั่ง ครัว จัดส่ง และวิเคราะห์ในระบบเดียว",
          description: "ระบบจัดการห่วงโซ่ร้านอาหาร: เมนู คำสั่ง ครัว จัดส่ง วิเคราะห์ เน้นการดำเนินงานและคุณภาพ",
          challenge: "รวมศูนย์การจัดการร้านอาหารหลายแห่งโดยไม่สูญเสียคุณภาพ",
          solution: "ระบบรวมสำหรับเมนู คำสั่ง ครัว การจัดส่ง และการวิเคราะห์",
          role: "Product strategy, B2B UX, operations design.",
          stack: "Web platform, real-time updates, analytics.",
          proof: "Market research, competitor analysis, user interviews.",
        },
        {
          id: "telegram-mini-apps",
          number: "006",
          name: "Telegram Mini Apps",
          type: "ชุดแอปมินิสำหรับ Telegram",
          status: "ทดลอง",
          progress: 35,
          link: null,
          tags: ["Telegram", "Mini Apps", "Bots", "Web3", "Experiments"],
          cardDescription: "ทดลองใน Telegram: เกม ยูทิลิตี และบอทเพื่อตรวจสอบไอเดียเร็ว",
          description: "ชุดแอปมินิทดลองใน Telegram: เกม ยูทิลิตี บอท สร้างต้นแบบเร็วและตรวจสอบแนวคิด",
          challenge: "ค้นหา product-market fit สำหรับระบบนิเวศ Telegram",
          solution: "การวนซ้ำอย่างรวดเร็ว การทดสอบ A/B ลูปข้อเสนอแนะ",
          role: "Product experiments, UX/UI, rapid prototyping.",
          stack: "Telegram Bot API, Web technologies, real-time updates.",
          proof: "Multiple working prototypes, user testing results.",
        },
      ],
    },
    // Process Section
    process: {
      caption: "PROCESS",
      title: "กระบวนการ",
      subtitle: "คนส่วนใหญ่ปิดหนึ่งหรือสองขั้นตอน ฉันสร้างระบบทั้งหมด",
      previousStep: "ขั้นตอนก่อนหน้า",
      nextStep: "ขั้นตอนถัดไป",
      artifactPlaceholderTitle: "อาร์ติแฟกต์เร็ว ๆ นี้",
      artifactPlaceholderHint: "วิธีการและโครงสร้างขั้นตอนอยู่ด้านล่าง",
      openGallery: "เปิด",
      stages: {
        1: {
          title: "ปัญหา",
          description: "ฉันกำหนดปัญหา แยกอาการจากสาเหตุ ระบุผู้ใช้ บริบท และเกณฑ์ความสำเร็จ",
          artifacts: ["Problem Statement", "User Interview", "JTBD", "Hypothesis", "Success Metrics"],
          logic: "Identify → Define → Validate → Measure",
        },
        2: {
          title: "วิจัย",
          description: "ฉันรวบรวมข้อมูล ศึกษาผู้ใช้ ตลาด คู่แข่ง และข้อจำกัดของผลิตภัณฑ์",
          artifacts: ["User Interviews", "Competitor Map", "JTBD", "Personas", "Insights"],
          logic: "Observe → Compare → Cluster → Insight",
        },
        3: {
          title: "ตรรกะผลิตภัณฑ์",
          description: "ฉันสร้างระบบจากความสับสน: สถานการณ์ ขอบเขต MVP ลำดับความสำคัญ เมตริก และกลยุทธ์การเปิดตัว",
          artifacts: ["User Journey", "Feature Map", "MVP Scope", "Roadmap", "Metrics"],
          logic: "Structure → Prioritize → Scope → Plan",
        },
        4: {
          title: "UX",
          description: "ฉันออกแบบสถานการณ์ผู้ใช้ สถานะหน้าจอ การนำทาง และจุดตัดสินใจหลัก",
          artifacts: ["User Flow", "Wireframes", "Screen States", "Edge Cases", "Prototype Logic"],
          logic: "Flow → States → Friction → Prototype",
        },
        5: {
          title: "UI",
          description: "ฉันเปลี่ยนตรรกะเป็นอินเตอร์เฟซ: ระบบภาพ ส่วนประกอบ สถานะ จังหวะ และความสามารถในการอ่าน",
          artifacts: ["Design System", "Components", "Typography", "Spacing", "UI States"],
          logic: "System → Components → States → Polish",
        },
        6: {
          title: "สถาปัตยกรรม AI",
          description: "ฉันออกแบบตรรกะ AI: พรอมต์ การสร้างเนื้อหา โครงสร้างข้อมูล การทำให้เป็นอัตโนมัติ และการควบคุมคุณภาพ",
          artifacts: ["Prompt System", "LLM Flow", "JSON Structure", "Automation", "QA Logic"],
          logic: "Input → Prompt → Model → Output → Feedback",
        },
        7: {
          title: "ต้นแบบ",
          description: "ฉันสร้างต้นแบบการทำงาน ทดสอบสถานการณ์ พฤติกรรม การเปลี่ยนแปลง และความรู้สึกของผลิตภัณฑ์",
          artifacts: ["Clickable Prototype", "Interaction Map", "Motion States", "Test Build", "Feedback Notes"],
          logic: "Build → Test → Fix → Repeat",
        },
        8: {
          title: "เปิดตัว",
          description: "ฉันนำผลิตภัณฑ์ไปเปิดตัว: การวิเคราะห์ ข้อเสนอแนะ การวนซ้ำ แผนงาน และเวอร์ชันถัดไป",
          artifacts: ["Launch Plan", "Analytics", "Feedback Loop", "Roadmap", "Iteration Backlog"],
          logic: "Ship → Measure → Learn → Improve",
        },
      },
    },
    // Experience Section
    experience: {
      title: "ประสบการณ์",
      intro: "15+ ปีในผลิตภัณฑ์และ IT",
      companies: [
        {
          id: "yandex",
          title: "Yandex",
          startYear: 2018,
          endYear: 2021,
          relevantSkills: ["big-tech", "marketplaces", "web-products", "ai-products"],
          blurb:
            "เหมือน Google + Amazon ของรัสเซีย — ค้นหา แผนที่ มาร์เก็ตเพลส คลาวด์ และ AI ที่ผู้ใช้หลายร้อยล้านคนใช้งาน",
          role: "Product & UX ในผลิตภัณฑ์ big-tech",
        },
        {
          id: "sber",
          title: "Sber",
          startYear: 2021,
          endYear: 2022,
          relevantSkills: ["big-tech", "ai-products", "web-products", "mobile"],
          blurb:
            "เหมือนธนาคารใหญ่ + ระบบนิเวศเทค (แนว SCB / Kasikorn + fintech) — AI คลาวด์ และบริการดิจิทัลสำหรับลูกค้าหลายล้านคน",
          role: "ผลิตภัณฑ์ AI และบริการดิจิทัล",
        },
        {
          id: "samokat",
          title: "Samokat",
          startYear: 2022,
          endYear: 2025,
          relevantSkills: ["foodtech", "marketplaces", "mobile", "web-products"],
          blurb:
            "เหมือน GrabMart / foodpanda Instant ของรัสเซีย — ส่งของเร็วมาก ผลิตภัณฑ์มือถือและโลจิสติกส์ในระดับเมืองใหญ่",
          role: "FoodTech และ UX มือถือ",
        },
        {
          id: "independent",
          title: "Independent",
          startYear: 2025,
          endYear: null,
          relevantSkills: ["edtech", "healthcare", "ai-products", "mobile"],
          blurb:
            "การสร้างผลิตภัณฑ์แบบอิสระ — AI, EdTech, Healthcare และระบบผลิตภัณฑ์แบบ end-to-end",
          role: "สร้างผลิตภัณฑ์แบบ solo",
        },
      ],
      items: [
        {
          id: "big-tech",
          title: "Big Tech",
          description: "ประสบการณ์การทำงานในบริษัทเทคโนโลยีขนาดใหญ่ที่มีผู้ใช้นับล้าน การปรับขนาดผลิตภัณฑ์ การทำงานกับข้อมูลขนาดใหญ่และการเพิ่มประสิทธิภาพประสบการณ์ผู้ใช้",
          details: "ทำงานที่ Yandex และ Sber ได้รับประสบการณ์ในการพัฒนาผลิตภัณฑ์สำหรับผู้ชมมวล การจัดการระบบที่ซับซ้อน และการทำงานในทีมข้ามหน้าที่",
        },
        {
          id: "ecommerce",
          title: "E-commerce",
          description: "ออกแบบและเพิ่มประสิทธิภาพแพลตฟอร์มการค้าอิเล็กทรอนิกส์ เน้นการแปลง การเดินทางของผู้ใช้ และการรวมระบบการชำระเงิน",
          details: "ประสบการณ์ในการสร้างและพัฒนาโซลูชัน e-commerce รวมถึงแคตตาล็อกผลิตภัณฑ์ ตะกร้าช้อปปิ้ง ชำระเงิน และการวิเคราะห์ยอดขาย",
        },
        {
          id: "marketplaces",
          title: "Marketplaces",
          description: "พัฒนาแพลตฟอร์มสองด้านที่ผู้ขายและผู้ซื้อพบกัน การสมดุลผลประโยชน์ของทั้งสองฝ่ายและการสร้างเอฟเฟกต์เครือข่าย",
          details: "ทำงานในตลาดรวมถึงการจัดการผู้ขาย การจัดอันดับ บทวิจารณ์ และกลไกการมีส่วนร่วม",
        },
        {
          id: "foodtech",
          title: "FoodTech",
          description: "สร้างผลิตภัณฑ์ในด้านการจัดส่งอาหารและการจัดการร้านอาหาร โลจิสติกส์ การรวมร้านอาหาร และการเพิ่มประสิทธิภาพการจัดส่ง",
          details: "ประสบการณ์ที่ Samokat และโครงการ FoodTech อื่น ๆ ทำงานกับโซลูชันผู้บริโภคและ B2B สำหรับร้านอาหาร",
        },
        {
          id: "edtech",
          title: "EdTech",
          description: "ออกแบบแพลตฟอร์มการศึกษาและระบบการเรียนรู้ การแบ่งเกม ความก้าวหน้าของผู้ใช้ และการเรียนรู้ที่ปรับตัวได้",
          details: "สร้างหลักสูตรแบบโต้ตอบ ระบบติดตามความก้าวหน้า และเส้นทางการเรียนรู้ส่วนบุคคล",
        },
        {
          id: "healthcare",
          title: "Healthcare",
          description: "พัฒนาโซลูชันทางการแพทย์และระบบการจัดการสุขภาพ การปฏิบัติตามกฎระเบียบ ความปลอดภัยของข้อมูล และความสะดวกของแพทย์",
          details: "ทำงานในระบบการจัดการผู้ป่วย บันทึกทางการแพทย์อิเล็กทรอนิกส์ และการรวมอุปกรณ์ทางการแพทย์",
        },
        {
          id: "ai-products",
          title: "AI products",
          description: "การรวมปัญญาประดิษฐ์ลงในผลิตภัณฑ์ผู้บริโภคและ B2B วิศวกรรมพรอมต์ LLM และการทำให้เป็นอัตโนมัติ",
          details: "ประสบการณ์ในการสร้างผู้ช่วย AI ระบบคำแนะนำ การทำให้เนื้อหาเป็นอัตโนมัติ และการรวม LLM สมัยใหม่",
        },
        {
          id: "mobile",
          title: "Mobile apps",
          description: "พัฒนาแอปพลิเคชันมือถือแบบเนทีฟและข้ามแพลตฟอร์ม iOS, Android, UX มือถือและการเพิ่มประสิทธิภาพประสิทธิการ",
          details: "ประสบการณ์กับ Swift, Kotlin และเฟรมเวิร์กข้ามแพลตฟอร์ม ทำงานในแอปที่มีการติดตั้งนับล้าน",
        },
        {
          id: "web-products",
          title: "Web products",
          description: "สร้างแอปพลิเคชันเว็บและ SPA React, Vue, TypeScript และสแต็กเว็บสมัยใหม่ การเพิ่มประสิทธิภาพประสิทธิการและ SEO",
          details: "ประสบการณ์ในการสร้างแอปพลิเคชันเว็บที่ซับซ้อน ตั้งแต่หน้าแรกอย่างง่ายไปจนถึงแพลตฟอร์มที่มีฟีเจอร์ครบถ้วนพร้อมการอัปเดตแบบเรียลไทม์",
        },
      ],
      timeline: "Yandex → Sber → Samokat → Independent Product Builder",
    },
    // Now Building Section
    nowBuilding: {
      title: "Now building",
      projects: [
        {
          id: "taika",
          name: "TAIKA",
          progress: 91,
          status: "MVP in progress",
          description: "ครูสอนภาษาไทย AI ส่วนบุคคลสำหรับผู้พูดภาษารัสเซีย",
          details: "แพลตฟอร์มรวมหลักสูตรแบบโต้ตอบ การฝึกเสียง เนื้อหา AI กลไกเกม และ UX มือถือแบบเนทีฟ เน้นภาษาสนทนาและการฝึกรายวัน",
        },
        {
          id: "hospital-ai",
          name: "Hospital AI",
          progress: 42,
          status: "MVP scope",
          description: "ผู้ช่วย AI สำหรับการนัดหมายแพทย์และการจัดเอกสาร",
          details: "อินเตอร์เฟซแพทย์พร้อมการบันทึกการนัดหมาย การถอดเสียงอัตโนมัติ โปรโตคอล AI-structured และการส่งออก PDF พัฒนาสำหรับคลินิกเล็ก ๆ ในประเทศไทย",
        },
        {
          id: "moo",
          name: "MOO",
          progress: 64,
          status: "Prototype",
          description: "บริการสมัครสมาชิกอาหารพร้อมการจัดส่วนประกอบอาหารแบบส่วนบุคคล",
          details: "บริการมือถือที่ผู้ใช้สร้างอาหารของตนเองจากหมวดหมู่และจานอาหารที่มีอยู่ เน้นการเลือกที่ง่าย ตะกร้าที่ชัดเจน และการสั่งซื้ำซ้ำที่ง่าย",
        },
        {
          id: "new-product",
          name: "New product",
          progress: 0,
          status: "Research",
          description: "ผลิตภัณฑ์ใหม่ในขั้นตอนการวิจัยและการตรวจสอบความเป็นไปได้",
          details: "ปัจจุบันอยู่ในการวิจัยตลาดเชิงลึก การสัมภาษณ์ผู้ใช้ และการสร้างขอบเขต MVP การอัปเดตจะเร็ว ๆ นี้",
        },
        {
          id: "secret",
          name: "Secret",
          progress: 0,
          status: "Coming soon",
          description: "โครงการลับที่อยู่ระหว่างการพัฒนา",
          details: "รายละเอียดจะเปิดเผยในภายหลัง ติดตามการอัปเดตบนโซเชียลมีเดีย และ Telegram",
        },
      ],
    },
    // Contact Section
    contact: {
      title: "มาสร้างกันเถอะ",
      links: {
        telegram: "https://t.me/bayshev",
        instagram: "https://instagram.com/bayshev",
        email: "mailto:sabaishev@icloud.com",
      },
      labels: {
        telegram: "Telegram",
        instagram: "Instagram",
        email: "Email",
      },
      form: {
        subtitle: "สร้างบรีฟในหนึ่งนาที — แค่แตะและเลื่อน ไม่ต้องพิมพ์",
        briefLabel: "Brief",
        next: "ถัดไป",
        submit: "ส่งบรีฟ",
        sent: "เปิดแล้ว",
        submitSubject: "Brief · VIKTOR.SYSTEM",
        submitMessage: "สวัสดี! อยากคุยเรื่องโปรเจกต์",
        summaryTitle: "สรุป",
        steps: {
          need: "ต้องการอะไร",
          domain: "อุตสาหกรรม",
          budget: "งบประมาณ",
          location: "ที่ตั้ง",
          timeline: "ไทม์ไลน์",
          channel: "ช่องทาง",
        },
        hints: {
          need: "เลือกได้หลายข้อ",
          domain: "เลือกได้หลายข้อ — ทุกอย่างที่ใกล้เคียงงาน",
          budget: "เลื่อนสไลเดอร์ สกุลเงินแตะครั้งเดียว",
          location: "ผลิตภัณฑ์จะอยู่ที่ไหน",
          timeline: "อยากเริ่มเมื่อไหร่",
          channel: "ส่งบรีฟไปที่ไหน",
        },
        summary: {
          need: "ต้องการ",
          domain: "อุตสาหกรรม",
          budget: "งบ",
          location: "ที่ตั้ง",
          timeline: "ไทม์ไลน์",
          channel: "ช่องทาง",
        },
        currencies: {
          RUB: "₽ RUB",
          THB: "฿ THB",
          USD: "$ USD",
        },
        options: {
          need: [
            { id: "mvp", label: "MVP / ต้นแบบ" },
            { id: "product", label: "ผลิตภัณฑ์ใหม่" },
            { id: "redesign", label: "รีดีไซน์" },
            { id: "ai", label: "ฟีเจอร์ AI" },
            { id: "mobile", label: "แอปมือถือ" },
            { id: "web", label: "เว็บผลิตภัณฑ์" },
            { id: "telegram-bot", label: "บอท Telegram" },
            { id: "workspace", label: "Workspace / เครื่องมือภายใน" },
            { id: "automation", label: "ออโตเมชัน" },
            { id: "audit", label: "ออดิต / ที่ปรึกษา" },
          ],
          domain: [
            { id: "fintech", label: "FinTech" },
            { id: "foodtech", label: "FoodTech" },
            { id: "edtech", label: "EdTech" },
            { id: "health", label: "Healthcare" },
            { id: "ecommerce", label: "E-commerce" },
            { id: "marketplace", label: "Marketplace" },
            { id: "saas", label: "SaaS / B2B" },
            { id: "telegram", label: "Telegram / บอท" },
            { id: "workspace", label: "Workspace / productivity" },
            { id: "ai-tools", label: "เครื่องมือ AI" },
            { id: "media", label: "Media / คอนเทนต์" },
            { id: "travel", label: "Travel / hospitality" },
            { id: "realestate", label: "Real Estate" },
            { id: "logistics", label: "Logistics" },
            { id: "hr", label: "HR / recruiting" },
            { id: "gaming", label: "Gaming / entertainment" },
            { id: "crypto", label: "Crypto / Web3" },
            { id: "other", label: "อื่นๆ" },
          ],
          location: [
            { id: "ru", label: "รัสเซีย" },
            { id: "th", label: "ไทย" },
            { id: "sea", label: "SEA / เอเชีย" },
            { id: "eu", label: "ยุโรป" },
            { id: "us", label: "สหรัฐฯ" },
            { id: "global", label: "ทั่วโลก" },
            { id: "remote", label: "Remote" },
          ],
          timeline: [
            { id: "asap", label: "เร็วที่สุด" },
            { id: "1m", label: "ภายในเดือน" },
            { id: "1-3m", label: "1–3 เดือน" },
            { id: "3m+", label: "3+ เดือน" },
            { id: "explore", label: "กำลังสำรวจ" },
          ],
          channel: [
            { id: "telegram", label: "Telegram" },
            { id: "email", label: "Email" },
            { id: "instagram", label: "Instagram" },
          ],
        },
      },
      footer: {
        tagline: "AI Product Builder จากไอเดียและ UX ถึงเปิดตัว",
        navTitle: "นำทาง",
        contactTitle: "ติดต่อ",
        rights: "สงวนลิขสิทธิ์",
        built: "Built as a personal OS.",
      },
    },
    // SEO
    seo: {
      title: "VIKTOR.SYSTEM — AI Product Builder",
      description: "ระบบโครงการส่วนบุคคลของวิกเตอร์: AI, UX/UI, mobile, web, automation and product strategy.",
    },
  },
};
